# Generated by Django 4.0.5 on 2022-06-28 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('account_number', models.CharField(max_length=20)),
                ('account_name', models.CharField(max_length=20)),
                ('account_type', models.CharField(max_length=20)),
                ('account_bank', models.CharField(max_length=20)),
                ('account_branch', models.CharField(max_length=20)),
                ('remarks', models.CharField(max_length=200)),
                ('purpose', models.CharField(max_length=20)),
                ('bank_code', models.CharField(max_length=20)),
                ('atm_code', models.CharField(max_length=20)),
                ('atm_location', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Withdraw',
                'db_table': 'withdraw',
                'ordering': ['-date'],
            },
        ),
    ]
